# Generated by Django 2.1 on 2018-08-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('excluido', models.BooleanField()),
                ('gols_mandante', models.IntegerField()),
                ('gols_visitante', models.IntegerField()),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandante', to='campeonatos.Time')),
                ('vistante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitante', to='campeonatos.Time')),
            ],
        ),
    ]
