# Generated by Django 2.1 on 2018-08-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0002_jogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('excluido', models.BooleanField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campeonatos.Campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='campeonato',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='campeonatos.Campeonato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='rodada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='campeonatos.Rodada'),
            preserve_default=False,
        ),
    ]
