# Generated by Django 2.1 on 2018-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_auto_20180826_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodada',
            name='numero',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
